yesense_pub:
    ros__parameters:
        serial_port: "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5B32028095-if00"
        baud_rate: 460800
        frame_id: "gyro_link"
        driver_type: "linux_serial"
        imu_topic_ros: "imu/data_raw"
        imu_topic: "imu_data"

